### ISSUE TITLE
npm run devmock

### ISSUE THREAD

**Issue by threetown** [thierryxing/Falcon#1]
package.json增加如下：

![image](https://user-images.githubusercontent.com/12680441/33824261-c85f3f06-de98-11e7-9afa-7735d4a744e4.png)

跑命令如下：
```bash
npm run mockdev
```
结果只把 npm run mock跑起来了，npm run dev没跑起来
![image](https://user-images.githubusercontent.com/12680441/33824359-1f5a09b2-de99-11e7-80e1-d7346c01f51c.png)

请大神指点，怎么能**跑这两个命令**

**Comment by thierryxing** [comment]
windows下面需要修改一下package.json下面的
 npm run mock & npm run dev
把 & 换成 |
