### ISSUE TITLE
server.js里怎么有require('underscore')？

### ISSUE THREAD

**Issue by threetown** [thierryxing/Falcon#2]
![image](https://user-images.githubusercontent.com/12680441/33831405-f21e3bde-deb2-11e7-91be-4cc9ca9b92bc.png)

**Comment by thierryxing** [comment]
代码中确实用到了：

```
// 支持加载多个db文件
const _ = require('underscore')
const path = require('path')
const fs = require('fs')
const mockDir = path.join(__dirname, 'data')
const base = {}
const files = fs.readdirSync(mockDir)
files.forEach((file) => {
  _.extend(base, require(path.resolve(mockDir, file)))
})
const router = jsonServer.router(base)
```

> npm install underscore
试试

**Comment by threetown** [comment]
是的，大神。我是直接从你这个**仓库里拔的代码**。

我看你的 `package.json` 里面没有 `underscore` 的依赖，所以我**最开始没安装，就报上面的错**了；
后来，无奈之下，安装了 underscore，就好了。

所以，很疑惑。**为什么你的不用装 underscore**？

**Comment by thierryxing** [comment]
这个库常用，所以加到全局中了，我补充一下
