### ISSUE TITLE
试运行了一下，app.js 8.1 M？

### ISSUE THREAD

**Issue by doocal** [thierryxing/Falcon#3]
一个JS接近10M，太夸张。。。。。要优化。

**Comment by thierryxing** [comment]
是这样的：在Dev模式下，JS没有压缩混淆和分割，所以很大。
最终在Production模式下的话（npm run build），app.js会只有98.5k
不过，确实有需要优化的地方，等项目完全搞定后，会尝试处理。

**Comment by thierryxing** [comment]
用NODE_ENV=production npm_config_report=true npm run build，分析了一下，主要是几个第三方依赖的库比较大：highlights.js和echarts.js，占了90%的大小。
