### ISSUE TITLE
为什么要引入jquery呢？不引入实现不了吗？

### ISSUE THREAD

**Issue by Chenberg** [thierryxing/Falcon#4]
jquery是操作dom的，不符合vue的理念，为什么还要引入呢？有哪些jquery组件是必须要用的吗？

**Comment by thierryxing** [comment]
因为用到了 
Adminlte 作为页面框架，而 Adminlte 是基于 Bootstrap 的，所以需要 jQuery 去实现一些 Dom 控制。

**Comment by Chenberg** [comment]
嗯，所以引入adminlte，主要是这个项目的视觉效果非常棒，但是vue的一些ui框架，也有如layout、栅格系统、各种表单控件等组件，只是视觉效果简陋些，能否不引入jquery和bootstrap，而利用这些ui系统实现adminlte的视觉效果呢？感觉仍然用jquery只是过渡方案。

**Comment by thierryxing** [comment]
完全没问题，我当时选择 Adminlte（Boostrap） 的原因就是用起来方便，不用自己写 CSS，而专注于虚拟 Dom 的开发。
如果有兴趣，你可以完全基于纯 Vue 实现同样的界面和交互。

**Comment by Chenberg** [comment]
我找了不少Vue后台框架，现在用的是花裤衩的vue-element-admin，基于element-ui的，界面看上去比较简陋，Adminlte很华丽但是不想再引入jquery了，如果能不引入jquery和bootstrap而能达到Adminlte的视觉效果，这样的ui才会最受欢迎。

**Comment by thierryxing** [comment]
可以试试这个框架：https://coreui.io/vue/

**Comment by Chenberg** [comment]
看了，确实不错，只是使用全部组件要买pro版，感谢！
